spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

kakao:
  redirect-uri: https://kauth.kakao.com/oauth/token

cloud:
  aws:
    s3:
      directory: dev