server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api

spring:
  profiles:
    active: local
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    log-startup-info: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${CLIENT_ID}   # REST API 키
            client-secret: ${CLIENT_SECRET}
            redirect-uri: ${REDIRECT_URI}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: <https://kauth.kakao.com/oauth/authorize>
            token-uri: <https://kauth.kakao.com/oauth/token>
            user-info-uri: <https://kapi.kakao.com/v2/user/me>
            user-name-attribute: id


  oauth:
    kakao:
      client-id: ${ClIENT_ID}
      url:
        auth: https://kauth.kakao.com
        api: https://kapi.kakao.com

jwt:
  secret-key: ${JWT_SECRET_KEY}

springdoc:
  packages-to-scan: com.ohyes.soolsool
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
